export const ORDER_CREATE_REQUEST = "ORDER_CREATE_REQUEST";
export const ORDER_CREATE_SUCCESS = "ORDER_CREATE_SUCCESS";
export const ORDER_CREATE_FAIL = "ORDER_CREATE_FAIL";

export const ORDER_DETAILS_REQUEST = "ORDER_DETAILS_REQUEST";
export const ORDER_DETAILS_SUCCESS = "ORDER_DETAILS_SUCCESS";
export const ORDER_DETAILS_FAIL = "ORDER_DETAILS_FAIL";

export const ORDER_LIST_MY_REQUEST = "ORDER_LIST_MY_REQUEST";
export const ORDER_LIST_MY_SUCCESS = "ORDER_LIST_MY_SUCCESS";
export const ORDER_LIST_MY_FAIL = "ORDER_LIST_MY_FAIL";
export const ORDER_LIST_MY_RESET = "ORDER_LIST_MY_RESET";

export const ORDER_LIST_REQUEST = "ORDER_LIST_REQUEST";
export const ORDER_LIST_SUCCESS = "ORDER_LIST_SUCCESS";
export const ORDER_LIST_FAIL = "ORDER_LIST_FAIL";

export const ORDER_TRAITEMENT_REQUEST = "ORDER_TRAITEMENT_REQUEST";
export const ORDER_TRAITEMENT_SUCCESS = "ORDER_TRAITEMENT_SUCCESS";
export const ORDER_TRAITEMENT_FAIL = "ORDER_TRAITEMENT_FAIL";
export const ORDER_TRAITEMENT_RESET = "ORDER_TRAITEMENT_RESET";

export const ORDER_PREPA_REQUEST = "ORDER_PREPA_REQUEST";
export const ORDER_PREPA_SUCCESS = "ORDER_PREPA_SUCCESS";
export const ORDER_PREPA_FAIL = "ORDER_PREPA_FAIL";
export const ORDER_PREPA_RESET = "ORDER_PREPA_RESET";

export const ORDER_DELIVER_REQUEST = "ORDER_DELIVER_REQUEST";
export const ORDER_DELIVER_SUCCESS = "ORDER_DELIVER_SUCCESS";
export const ORDER_DELIVER_FAIL = "ORDER_DELIVER_FAIL";
export const ORDER_DELIVER_RESET = "ORDER_DELIVER_RESET";

export const ORDER_CANCEL_REQUEST = "ORDER_CANCEL_REQUEST";
export const ORDER_CANCEL_SUCCESS = "ORDER_CANCEL_SUCCESS";
export const ORDER_CANCEL_FAIL = "ORDER_CANCEL_FAIL";
export const ORDER_CANCEL_RESET = "ORDER_CANCEL_RESET";

export const ORDER_PAID_REQUEST = "ORDER_PAID_REQUEST";
export const ORDER_PAID_SUCCESS = "ORDER_PAID_SUCCESS";
export const ORDER_PAID_FAIL = "ORDER_PAID_FAIL";
export const ORDER_PAID_RESET = "ORDER_PAID_RESET";

export const ORDER_DELIVERED_BY_REQUEST = "ORDER_DELIVERED_BY_REQUEST";
export const ORDER_DELIVERED_BY_SUCCESS = "ORDER_DELIVERED_BY_SUCCESS";
export const ORDER_DELIVERED_BY_FAIL = "ORDER_DELIVERED_BY_FAIL";
export const ORDER_DELIVERED_BY_RESET = "ORDER_DELIVERED_BY_RESET";
